#ifndef NOTIFICATION_TYPE_H
#define NOTIFICATION_TYPE_H

enum NotificationType { NT_NONE, NT_CONTROLS, NT_UNDER_ATTACK, NT_FLEE,
                        NT_HULL_CRITICAL, NT_ENGINES_CRITICAL, NT_WEAPONS_CRITICAL,
                        NT_OBJECTIVE_SEEK, NT_OBJECTIVE_DESTROY, NT_OBJECTIVE_ESCAPE,
                        NT_COMMENT_ONE, NT_COMMENT_TWO, NT_COMMENT_THREE };

#endif
